"""Validate documentation-led architecture playbook assets."""

from __future__ import annotations

import argparse
import re
from pathlib import Path

REPORT_PATH = Path("docs/validation-report.md")

REQUIRED_FILES = [
    Path("README.md"),
    Path("docs/00-executive-brief.md"),
    Path("docs/01-problem-statement.md"),
    Path("docs/02-current-state.md"),
    Path("docs/03-target-state.md"),
    Path("docs/04-source-to-output-map.md"),
    Path("docs/05-data-quality-controls.md"),
    Path("docs/06-kpi-dictionary.md"),
    Path("docs/07-operating-model.md"),
    Path("docs/08-implementation-roadmap.md"),
    Path("docs/09-risks-and-limitations.md"),
    Path("docs/10-handover-pack.md"),
    Path("diagrams/README.md"),
    Path("templates/architecture-decision-record-template.md"),
    Path("templates/data-quality-rule-template.md"),
    Path("templates/kpi-definition-template.md"),
    Path("templates/reporting-requirements-template.md"),
    Path("templates/stakeholder-review-template.md"),
]

REQUIRED_DIAGRAMS = [
    Path("diagrams/current-state-flow.mmd"),
    Path("diagrams/source-to-output-flow.mmd"),
    Path("diagrams/reporting-lifecycle.mmd"),
    Path("diagrams/assurance-control-loop.mmd"),
]

LOCAL_LINK_RE = re.compile(r"\[[^\]]+\]\((?!https?://|mailto:|#)([^)#]+)(?:#[^)]+)?\)")


def _check_required_files(errors: list[str], notes: list[str]) -> None:
    for path in REQUIRED_FILES:
        if not path.exists():
            errors.append(f"missing required file: {path}")
        elif not path.read_text(encoding="utf-8").lstrip().startswith("#"):
            errors.append(f"{path}: expected first meaningful line to be a markdown heading")
    notes.append(f"Checked {len(REQUIRED_FILES)} required markdown assets")


def _check_diagrams(errors: list[str], notes: list[str]) -> None:
    for path in REQUIRED_DIAGRAMS:
        if not path.exists():
            errors.append(f"missing required diagram: {path}")
            continue
        text = path.read_text(encoding="utf-8")
        if "flowchart" not in text and "graph" not in text and "erDiagram" not in text:
            errors.append(f"{path}: does not look like Mermaid diagram content")
    notes.append(f"Checked {len(REQUIRED_DIAGRAMS)} Mermaid diagrams")


def _check_local_links(errors: list[str], notes: list[str]) -> None:
    markdown_files = sorted(Path(".").glob("**/*.md"))
    checked_links = 0
    for markdown_file in markdown_files:
        if ".git" in markdown_file.parts:
            continue
        text = markdown_file.read_text(encoding="utf-8")
        for match in LOCAL_LINK_RE.finditer(text):
            checked_links += 1
            target = match.group(1).strip()
            if target.startswith("<") and target.endswith(">"):
                target = target[1:-1]
            target_path = (markdown_file.parent / target).resolve()
            if not target_path.exists():
                errors.append(f"{markdown_file}: broken local link to {target}")
    if checked_links < 10:
        errors.append(
            "expected at least 10 local markdown links so the playbook is navigable"
        )
    notes.append(f"Checked {checked_links} local markdown links")


def _write_report(notes: list[str]) -> None:
    REPORT_PATH.write_text(
        "\n".join(
            [
                "# Validation Report",
                "",
                "This report is generated by `scripts/validate_playbook_assets.py`.",
                "",
                "## Checks",
                "",
                *[f"- {note}" for note in notes],
                "",
                "## Current Verdict",
                "",
                "The playbook has the minimum structure expected for review: executive brief, numbered documents, Mermaid diagrams, templates, and validation checks. It is still a portfolio architecture artifact, not proof of a production implementation.",
                "",
            ]
        ),
        encoding="utf-8",
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write-report", action="store_true")
    args = parser.parse_args()

    errors: list[str] = []
    notes: list[str] = []

    _check_required_files(errors, notes)
    _check_diagrams(errors, notes)
    _check_local_links(errors, notes)

    if errors:
        for error in errors:
            print(f"ERROR: {error}")
        return 1

    if args.write_report:
        _write_report(notes)
        notes.append(f"Wrote {REPORT_PATH}")

    for note in notes:
        print(note)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
